- name: Setup VM for Todo App
  hosts: vm
  become: yes
  tasks:

    - name: Remove old Docker list if exists
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: yes  # صح، على مستوى الـ task

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker.list
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
      ignore_errors: yes  # كمان هنا task-level

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
